version: '3.4'
services:
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=secret"
    ports:
      - "5432:5432"
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  service:
    build:
      context: ./src
      dockerfile: Dockerfile.service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__State=host=postgres;user id=postgres;password=secret;database=SampleService;
      - RabbitMqTransport__Host=rabbitmq
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ${PWD}/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1777:1777"
      - "9411:9411"
      - "9943:9943"
      - "6831:6831"
      - "6832:6832"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "55681:55681"
  api:
    build:
      context: ./src
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMqTransport__Host=rabbitmq
